### ISSUE TITLE
DecentExposure 3.0.0

### ISSUE THREAD

**Issue by mattpolito** [netguru/decent_decoration#6]
Hello, just wanted to make you aware that DecentExposure is about to release a v3.0.0. Since I noticed this library interacts with it and the API has changed a bit, just wanted to give you a heads up. 

There is a mechanism for decorating built in now if you want to check it out here:
https://github.com/hashrocket/decent_exposure#decorate

Let me know if you have any questions.

**Comment by timurvafin** [comment]
@mattpolito idea behind `decent_decoration` is to decorate object only for view layer. While `decorate` option in `decent_exposure 3.0` decorates object for controller layer as well.

**Comment by mattpolito** [comment]
I understand, just wanted you to be aware of the changes since you directly interact with the library.
